apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: heimdall-agent
  labels:
    app: heimdall-agent
    component: agent
spec:
  selector:
    matchLabels:
      app: heimdall-agent
  template:
    metadata:
      labels:
        app: heimdall-agent
    spec:
      hostPID: true
      serviceAccountName: heimdall-agent
      containers:
      - name: agent
        image: heimdall-agent:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        env:
        - name: SERVER_ADDR
          value: "heimdall-server:50051"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: AGENT_K8S_ENRICH
          value: "true"
        - name: AGENT_DIAGNOSTICS_INTERVAL
          value: "15s"
        volumeMounts:
        - name: debugfs
          mountPath: /sys/kernel/debug
        - name: bpffs
          mountPath: /sys/fs/bpf
      volumes:
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      - name: bpffs
        hostPath:
          path: /sys/fs/bpf
